# Generated by Django 3.1.6 on 2021-05-05 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('title', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('time_days', models.PositiveIntegerField(default='')),
                ('time_hours', models.PositiveIntegerField()),
                ('time_minutes', models.PositiveIntegerField()),
                ('time_now', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField(max_length=1500)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('title', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Arms', 'Arms'), ('Abs', 'Abs'), ('Chest', 'Chest'), ('Back', 'Back'), ('Legs', 'Legs'), ('Glutes', 'Glutes'), ('Shoulders', 'Shoulders')], max_length=60, null=True)),
                ('rpe', models.CharField(choices=[('1: Resting', '1: Resting'), ('2: Minimum Activity', '2: Minimum Activity'), ('3-4: Light Activity', '3-4: Light Activity'), ('5-6: Moderate Activity', '5-6: Moderate Activity'), ('7-8: Hard Activity', '7-8: Hard Activity'), ('9: Very Hard Activity', '9: Very Hard Activity'), ('10: Maximal Exertion', '10: Maximal Exertion')], max_length=60, null=True)),
                ('equipment', models.CharField(choices=[('Barbell', 'Barbell'), ('Bench', 'Bench'), ('Dumbbell', 'Dumbbell'), ('Gym Mat', 'Gym Mat'), ('Incline Bench', 'Incline Bench'), ('Kettlebell', 'Kettlebell'), ('Pull-Up Bar', 'Pull-Up Bar'), ('SZ-Bar', 'SZ-Bar'), ('Swiss Ball', 'Swiss Ball'), ('Rowing Machine', 'Rowing Machine'), ('Exercise Ball', 'Exercise Ball'), ('Stationary Bikes', 'Stationary Bikes'), ('Ellipticals', 'Ellipticals'), ('Treadmill', 'Treadmill'), ('None', 'None')], max_length=60, null=True)),
                ('reps', models.PositiveIntegerField()),
                ('time', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=1500)),
                ('points', models.PositiveIntegerField()),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
