# Generated by Django 3.1.6 on 2021-05-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='time_now',
            field=models.TextField(null=True),
        ),
    ]
